// this is for edit the code
// this is yuvraj
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

// author is yuvraj and made in netbeans and also with team
// and trying to make this as collobrative software chages done
// opened in netbeans

// next tutorial of github

// this is to trying pull request
public class StudentInventory extends javax.swing.JFrame {

  
    int cols,cols1,cols2 =0;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    Connection con = null;
    Connection con1 = null;
    Connection con2 = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst = null;
    String url = "jdbc:mysql://localhost:3306/studentmanagement";
    String userid = "root";
    String userPass = "Bright@2009";
    String url1 = "jdbc:mysql://localhost:3306/studentsoftware";
    
    
    public StudentInventory() {
        initComponents();
        showData();
        showTableData();
        showTeacherData();
        UsersPanel.setVisible(false);
        StudentsPanel.setVisible(false);
        TeachersPanel.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        UserTab = new javax.swing.JLabel();
        HeadingTab = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TeachersTab = new javax.swing.JLabel();
        StudentTab = new javax.swing.JLabel();
        CloseTab = new javax.swing.JLabel();
        LogOutTab = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        TABSPANEL = new javax.swing.JPanel();
        UsersPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        UserNameTxt = new javax.swing.JTextField();
        EmailIdTxt = new javax.swing.JTextField();
        BranchAddressTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        RefreshBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        SearchTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tab = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LastNameTxt = new javax.swing.JTextField();
        FirstNameTxt = new javax.swing.JTextField();
        UserPassTxt = new javax.swing.JTextField();
        StudentsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        StudentNameTxt = new javax.swing.JTextField();
        FatherTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        BatchNameTxt = new javax.swing.JTextField();
        MotherTxt2 = new javax.swing.JTextField();
        NewClass = new javax.swing.JTextField();
        BranchAddTxt = new javax.swing.JTextField();
        StudentSaveBtn = new javax.swing.JButton();
        StudentUpdateBtn = new javax.swing.JButton();
        StudentRefreshBtn = new javax.swing.JButton();
        StudentRefreshBtn1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        StudentSearchTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        TeachersPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TeacherNameTxt = new javax.swing.JTextField();
        TeacherEmailTxt = new javax.swing.JTextField();
        TeacherSubjectTxt = new javax.swing.JTextField();
        TeacherNumberTxt = new javax.swing.JTextField();
        TeacherSavebtn = new javax.swing.JButton();
        TeacherUpdateBtn = new javax.swing.JButton();
        TeacherDataDeleteBtn = new javax.swing.JButton();
        TeacherDataRefreshBtn = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        TeacherNameTxt1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBar.setBackground(new java.awt.Color(0, 0, 0));

        UserTab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UserTab.setForeground(new java.awt.Color(255, 255, 255));
        UserTab.setText("Users");
        UserTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTabMouseClicked(evt);
            }
        });

        HeadingTab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        HeadingTab.setForeground(new java.awt.Color(255, 255, 255));
        HeadingTab.setText("Student Management");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\devis\\OneDrive\\Desktop\\Man Reading a Book.png")); // NOI18N

        TeachersTab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TeachersTab.setForeground(new java.awt.Color(255, 255, 255));
        TeachersTab.setText("Teachers");
        TeachersTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TeachersTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeachersTabMouseClicked(evt);
            }
        });

        StudentTab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        StudentTab.setForeground(new java.awt.Color(255, 255, 255));
        StudentTab.setText("Students");
        StudentTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTabMouseClicked(evt);
            }
        });

        CloseTab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CloseTab.setForeground(new java.awt.Color(255, 255, 255));
        CloseTab.setText("Close");
        CloseTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseTabMouseClicked(evt);
            }
        });

        LogOutTab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LogOutTab.setForeground(new java.awt.Color(255, 255, 255));
        LogOutTab.setText("Log Out");
        LogOutTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOutTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutTabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HeadingTab, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TeachersTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CloseTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogOutTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeadingTab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(UserTab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(StudentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(TeachersTab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(CloseTab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(LogOutTab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        getContentPane().add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        UsersPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User's Login Data");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Name");

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("User Password");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Branch Add.");

        updateBtn.setBackground(new java.awt.Color(255, 124, 97));
        updateBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        RefreshBtn.setBackground(new java.awt.Color(255, 124, 97));
        RefreshBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RefreshBtn.setText("REFRESH");
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(255, 124, 97));
        DeleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Search By Name");

        SearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxtActionPerformed(evt);
            }
        });
        SearchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTxtKeyReleased(evt);
            }
        });

        Tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Second Name", "User Name", "Email Id", "User Password", "Branch Address"
            }
        ));
        Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tab);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("First Name");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Last Name");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Email Id");

        javax.swing.GroupLayout UsersPanelLayout = new javax.swing.GroupLayout(UsersPanel);
        UsersPanel.setLayout(UsersPanelLayout);
        UsersPanelLayout.setHorizontalGroup(
            UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersPanelLayout.createSequentialGroup()
                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 634, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(28, 28, 28)
                        .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UsersPanelLayout.createSequentialGroup()
                        .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UsersPanelLayout.createSequentialGroup()
                                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UsersPanelLayout.createSequentialGroup()
                                        .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(UserPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(UsersPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UsersPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UsersPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EmailIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(UsersPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BranchAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(UsersPanelLayout.createSequentialGroup()
                                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UsersPanelLayout.setVerticalGroup(
            UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(UsersPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BranchAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(UsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        StudentsPanel.setBackground(new java.awt.Color(51, 51, 51));
        StudentsPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Data");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student Name");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Father's Name");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mother's Name");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Class");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Batch Name");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Branch Address");

        StudentSaveBtn.setBackground(new java.awt.Color(255, 215, 139));
        StudentSaveBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        StudentSaveBtn.setText("SAVE");
        StudentSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentSaveBtnActionPerformed(evt);
            }
        });

        StudentUpdateBtn.setBackground(new java.awt.Color(255, 215, 139));
        StudentUpdateBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        StudentUpdateBtn.setText("UPDATE");
        StudentUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentUpdateBtnActionPerformed(evt);
            }
        });

        StudentRefreshBtn.setBackground(new java.awt.Color(255, 215, 139));
        StudentRefreshBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        StudentRefreshBtn.setText("REFRESH");
        StudentRefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentRefreshBtnActionPerformed(evt);
            }
        });

        StudentRefreshBtn1.setBackground(new java.awt.Color(255, 215, 139));
        StudentRefreshBtn1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        StudentRefreshBtn1.setText("DELETE");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Search By Name");

        StudentSearchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                StudentSearchTxtKeyReleased(evt);
            }
        });

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Student Name", "Father's Name", "Mother's Name", "Address", "Class", "Batch Name", "Branch Address"
            }
        ));
        Table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table2);

        javax.swing.GroupLayout StudentsPanelLayout = new javax.swing.GroupLayout(StudentsPanel);
        StudentsPanel.setLayout(StudentsPanelLayout);
        StudentsPanelLayout.setHorizontalGroup(
            StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsPanelLayout.createSequentialGroup()
                .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StudentNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FatherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentsPanelLayout.createSequentialGroup()
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BatchNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MotherTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewClass, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BranchAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(StudentsPanelLayout.createSequentialGroup()
                .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StudentsPanelLayout.createSequentialGroup()
                                .addComponent(StudentSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StudentUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StudentRefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(StudentsPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(StudentRefreshBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(StudentsPanelLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        StudentsPanelLayout.setVerticalGroup(
            StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsPanelLayout.createSequentialGroup()
                .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StudentsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StudentSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentsPanelLayout.createSequentialGroup()
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FatherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MotherTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BatchNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BranchAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(StudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudentRefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(StudentRefreshBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(StudentsPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );

        TeachersPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teachers Data");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Name");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Email Id");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Subject");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Phone Number");

        TeacherSavebtn.setBackground(new java.awt.Color(209, 193, 139));
        TeacherSavebtn.setText("SAVE");
        TeacherSavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherSavebtnActionPerformed(evt);
            }
        });

        TeacherUpdateBtn.setBackground(new java.awt.Color(209, 193, 139));
        TeacherUpdateBtn.setText("UPDATE");
        TeacherUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherUpdateBtnActionPerformed(evt);
            }
        });

        TeacherDataDeleteBtn.setBackground(new java.awt.Color(209, 193, 139));
        TeacherDataDeleteBtn.setText("DELETE");
        TeacherDataDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherDataDeleteBtnActionPerformed(evt);
            }
        });

        TeacherDataRefreshBtn.setBackground(new java.awt.Color(209, 193, 139));
        TeacherDataRefreshBtn.setText("REFRESH");
        TeacherDataRefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherDataRefreshBtnActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Search By Name");

        TeacherNameTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TeacherNameTxt1KeyReleased(evt);
            }
        });

        Table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Email Id", "Subject", "Phone Number"
            }
        ));
        Table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table3);

        javax.swing.GroupLayout TeachersPanelLayout = new javax.swing.GroupLayout(TeachersPanel);
        TeachersPanel.setLayout(TeachersPanelLayout);
        TeachersPanelLayout.setHorizontalGroup(
            TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeachersPanelLayout.createSequentialGroup()
                        .addGroup(TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TeacherNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(TeachersPanelLayout.createSequentialGroup()
                        .addGroup(TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TeachersPanelLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TeacherNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TeachersPanelLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TeacherEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TeachersPanelLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TeacherSubjectTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TeachersPanelLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TeacherNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TeachersPanelLayout.createSequentialGroup()
                                .addComponent(TeacherSavebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TeacherUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TeacherDataDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TeachersPanelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(TeacherDataRefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        TeachersPanelLayout.setVerticalGroup(
            TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeacherNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeachersPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeacherNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeacherEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeacherSubjectTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeacherNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(TeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeacherSavebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeacherUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeacherDataDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(TeacherDataRefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(TeachersPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout TABSPANELLayout = new javax.swing.GroupLayout(TABSPANEL);
        TABSPANEL.setLayout(TABSPANELLayout);
        TABSPANELLayout.setHorizontalGroup(
            TABSPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TABSPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(StudentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(TABSPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TeachersPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TABSPANELLayout.setVerticalGroup(
            TABSPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TABSPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(StudentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(TABSPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TeachersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(TABSPANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1220, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTabMouseClicked
        // TODO add your handling code here:
        UsersPanel.setVisible(true);
        StudentsPanel.setVisible(false);
    }//GEN-LAST:event_UserTabMouseClicked

    private void StudentTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTabMouseClicked
        // TODO add your handling code here:
        UsersPanel.setVisible(false);
        StudentsPanel.setVisible(true);
    }//GEN-LAST:event_StudentTabMouseClicked

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Tab.getModel();
        model.setRowCount(0);
        showData();
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void SearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTxtActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:\
                DefaultTableModel model = (DefaultTableModel)Tab.getModel();
                int sr = Tab.getSelectedRow();
                try {
            con = DriverManager.getConnection(url, userid, userPass);
            int id = Integer.parseInt(model.getValueAt(sr, 0).toString());
            pst = con.prepareStatement("delete from user where id =?");
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Record Delete Sucessfully !"); 
            FirstNameTxt.setText("");
            LastNameTxt.setText("");
            UserNameTxt.setText("");
            EmailIdTxt.setText("");
            UserPassTxt.setText("");
            BranchAddressTxt.setText("");
        } catch (Exception e) {
        }

    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel)Tab.getModel();
        int sr = Tab.getSelectedRow();
        try {
            con = DriverManager.getConnection(url, userid, userPass);
            int id = Integer.parseInt(model.getValueAt(sr, 0).toString());
            pst = con.prepareStatement("update user set firstname = ?,lastname=?,username=?,emailid=?,userpassword=?,branchaddress =? where id = ?");
            pst.setString(1,FirstNameTxt.getText() );
             pst.setString(2,LastNameTxt.getText() );
              pst.setString(3,UserNameTxt.getText() );
               pst.setString(4,EmailIdTxt.getText() );
                pst.setString(5,UserPassTxt.getText() );
                 pst.setString(6,BranchAddressTxt.getText() );
                  pst.setInt(7,id );
            pst.executeUpdate();
              JOptionPane.showMessageDialog(null,"Record Updated Sucessfully !"); 

            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Record Not Updated Sucessfully !"); 

        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Tab.getModel();
        int sr = Tab.getSelectedRow();
        FirstNameTxt.setText(model.getValueAt(sr, 1).toString());
        LastNameTxt.setText(model.getValueAt(sr, 2).toString());
        UserNameTxt.setText(model.getValueAt(sr, 3).toString());
        EmailIdTxt.setText(model.getValueAt(sr, 4).toString());
        UserPassTxt.setText(model.getValueAt(sr, 5).toString());
        BranchAddressTxt.setText(model.getValueAt(sr, 6).toString());

    }//GEN-LAST:event_TabMouseClicked

    private void TeachersTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeachersTabMouseClicked
        // TODO add your handling code here:
        UsersPanel.setVisible(false);
        StudentsPanel.setVisible(false);
        TeachersPanel.setVisible(true);
        
    }//GEN-LAST:event_TeachersTabMouseClicked

    private void StudentSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentSaveBtnActionPerformed
        // TODO add your handling code here:
        if (StudentNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter Input!");
        }
        else{
            try {
                int classNo = Integer.parseInt(NewClass.getText());
                con1 = DriverManager.getConnection(url1,userid,userPass);
                pst1= con1.prepareStatement("insert into stdinfo (StudentName,Fathersname,Mothersname,Address,class,Batchname,BranchAdd) values(?,?,?,?,?,?,?) ");
                pst1.setString(1, StudentNameTxt.getText());
                pst1.setString(2, FatherTxt.getText());
                pst1.setString(3, MotherTxt2.getText());
                pst1.setString(4, AddressTxt.getText());
                pst1.setInt(5, classNo);
                pst1.setString(6, BatchNameTxt.getText());
                pst1.setString(7, BranchAddTxt.getText());
                pst1.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data successfully saved");
                StudentNameTxt.setText("");
                FatherTxt.setText("");
                MotherTxt2.setText("");
                AddressTxt.setText("");
                NewClass.setText("");
                BatchNameTxt.setText("");
                BranchAddTxt.setText("");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error !"+ e.getMessage());
            }
        }
    }//GEN-LAST:event_StudentSaveBtnActionPerformed

    private void StudentUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentUpdateBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel)Table2.getModel();
        int Select = Table2.getSelectedRow();
        try {
            int classNo = Integer.parseInt(NewClass.getText());
             con1 = DriverManager.getConnection(url1,userid,userPass);
             int id1 = Integer.parseInt(model1.getValueAt(Select, 0).toString());
             pst1 = con.prepareStatement("update stdinfo where StudentName=?, Fathersname=? ,Mothersname =?,Address =?,class =?,Batchname =?,BranchAdd =? where id1 = ?");
             pst1.setString(1, StudentNameTxt.getText());
                pst1.setString(2, FatherTxt.getText());
                pst1.setString(3, MotherTxt2.getText());
                pst1.setString(4, AddressTxt.getText());
                pst1.setInt(5, classNo);
                pst1.setString(6, BatchNameTxt.getText());
                pst1.setString(7, BranchAddTxt.getText());
                pst1.setInt(8, id1);
                pst1.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data updated successfully ");
                StudentNameTxt.setText("");
                FatherTxt.setText("");
                MotherTxt2.setText("");
                AddressTxt.setText("");
                NewClass.setText("");
                BatchNameTxt.setText("");
                BranchAddTxt.setText("");
                
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error"+ e.getMessage());
        }
    }//GEN-LAST:event_StudentUpdateBtnActionPerformed

    private void StudentRefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentRefreshBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel)Table2.getModel();
        model1.setRowCount(0);
        showTableData();
        
    }//GEN-LAST:event_StudentRefreshBtnActionPerformed

    private void TeacherSavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherSavebtnActionPerformed
        // TODO add your handling code here:
        try {
             con2 = DriverManager.getConnection(url1, userid, userPass);
             pst2 = con2.prepareStatement("insert into teachers (name,email,subject,phone) values (?,?,?,?)");
             pst2.setString(1, TeacherNameTxt.getText());
             pst2.setString(2, TeacherEmailTxt.getText());
             pst2.setString(3,TeacherSubjectTxt.getText());
             pst2.setString (4,TeacherNumberTxt.getText());
             pst2.executeUpdate();
             JOptionPane.showMessageDialog(this, "Data Saved successfully ");
             TeacherNameTxt.setText("");
            TeacherEmailTxt.setText("");
            TeacherSubjectTxt.setText("");
            TeacherNumberTxt.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error!  "+e.getMessage());
        }
    }//GEN-LAST:event_TeacherSavebtnActionPerformed

    private void TeacherUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherUpdateBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel)Table3.getModel();
        int SelectedRow = Table3.getSelectedRow();
        try {
            int id2 = Integer.parseInt(model2.getValueAt(SelectedRow, 0).toString());
            con2 = DriverManager.getConnection(url1, userid, userPass);
            pst2 = con2.prepareStatement("update studentsoftware.teachers set name = ?, email = ?,subject = ?,phone= ? where id = ? ");
            pst2.setString(1, TeacherNameTxt.getText());
             pst2.setString(2, TeacherEmailTxt.getText());
             pst2.setString(3,TeacherSubjectTxt.getText());
             pst2.setString (4,TeacherNumberTxt.getText());
             pst2.setInt(5, id2);
             pst2.executeUpdate();   
             JOptionPane.showMessageDialog(this, "successfully updated");
             TeacherNameTxt.setText("");
            TeacherEmailTxt.setText("");
            TeacherSubjectTxt.setText("");
            TeacherNumberTxt.setText("");
        }catch(SQLException e){
            
        }
    }//GEN-LAST:event_TeacherUpdateBtnActionPerformed
public void searchUserData(String str){
    DefaultTableModel newModel = (DefaultTableModel) Tab.getModel();
    TableRowSorter<DefaultTableModel> trs  = new TableRowSorter<>(newModel);
    Tab.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter("(?i)" + str));
}
public void searchStudentData(String str){
    DefaultTableModel newModel = (DefaultTableModel) Table2.getModel();
    TableRowSorter<DefaultTableModel> trs  = new TableRowSorter<>(newModel);
    Table2.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter("(?i)" + str));
}
public void searchTeacherData(String str){
    DefaultTableModel newModel = (DefaultTableModel) Table3.getModel();
    TableRowSorter<DefaultTableModel> trs  = new TableRowSorter<>(newModel);
    Table3.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter("(?i)" + str));
}



    private void TeacherDataRefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherDataRefreshBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel)Table3.getModel();
        model2.setRowCount(0);
        showTeacherData();
    }//GEN-LAST:event_TeacherDataRefreshBtnActionPerformed

    private void TeacherDataDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherDataDeleteBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel)Table3.getModel();
        int SelectedRow = Table3.getSelectedRow();
        try {
            int id1 = Integer.parseInt(model2.getValueAt(SelectedRow, 0).toString());
            con2 = DriverManager.getConnection(url1, userid, userPass);
            pst2 = con2.prepareStatement("delete from studentsoftware.teachers where id = ?");
            pst2.setInt(1, id1);
            pst2.executeUpdate();
            JOptionPane.showMessageDialog(this, "successfully deleted");
            TeacherNameTxt.setText("");
            TeacherEmailTxt.setText("");
            TeacherSubjectTxt.setText("");
            TeacherNumberTxt.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error!"+e.getMessage()); 
        }
        
    }//GEN-LAST:event_TeacherDataDeleteBtnActionPerformed

    private void Table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel)Table3.getModel();
        int TeacherRow = Table3.getSelectedRow();
        TeacherNameTxt.setText(model2.getValueAt(TeacherRow, 1).toString());
        TeacherEmailTxt.setText(model2.getValueAt(TeacherRow, 2).toString());
        TeacherSubjectTxt.setText(model2.getValueAt(TeacherRow, 3).toString());
        TeacherNumberTxt.setText(model2.getValueAt(TeacherRow, 4).toString());
        
    }//GEN-LAST:event_Table3MouseClicked

    private void Table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseClicked
        // TODO add your handling code here:
       
        DefaultTableModel model1 = (DefaultTableModel)Table2.getModel();
        int StudentRow= Table2.getSelectedRow();
        StudentNameTxt.setText(model1.getValueAt(StudentRow, 1).toString());
        FatherTxt.setText(model1.getValueAt(StudentRow, 2).toString());
        MotherTxt2.setText(model1.getValueAt(StudentRow, 3).toString());
        AddressTxt.setText(model1.getValueAt(StudentRow, 4).toString());
        NewClass.setText(model1.getValueAt(StudentRow, 5).toString());
        BatchNameTxt.setText(model1.getValueAt(StudentRow, 6).toString());
        BranchAddTxt.setText(model1.getValueAt(StudentRow, 7).toString());
        
    }//GEN-LAST:event_Table2MouseClicked

    private void CloseTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseTabMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CloseTabMouseClicked

    private void LogOutTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutTabMouseClicked
        // TODO add your handling code here:
        Login_system ls = new Login_system();
        ls.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogOutTabMouseClicked

    private void SearchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTxtKeyReleased
        // TODO add your handling code here:
        String SearchUserTxt = SearchTxt.getText();
        searchUserData(SearchUserTxt);
    }//GEN-LAST:event_SearchTxtKeyReleased

    private void StudentSearchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StudentSearchTxtKeyReleased
        // TODO add your handling code here:
        String SearchUserTxt = StudentSearchTxt.getText();
        searchStudentData(SearchUserTxt);
    }//GEN-LAST:event_StudentSearchTxtKeyReleased

    private void TeacherNameTxt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TeacherNameTxt1KeyReleased
        // TODO add your handling code here:
        String SearchUserTxt = TeacherNameTxt1.getText();
        searchTeacherData(SearchUserTxt);
    }//GEN-LAST:event_TeacherNameTxt1KeyReleased
public void showData(){
        try {
            con = DriverManager.getConnection(url, userid, userPass);
            pst = con.prepareStatement("select * from user");
            rs = pst.executeQuery();
            ResultSetMetaData rsmt = rs.getMetaData();
            cols=rsmt.getColumnCount();
            DefaultTableModel model=(DefaultTableModel)Tab.getModel();
            while(rs.next()){
                Vector v = new Vector();
                for (int i = 1; i<=cols;i++){
                    v.add(rs.getShort("id"));
                    v.add(rs.getString("firstname"));
                    v.add(rs.getString("lastname"));
                    v.add(rs.getString("username"));
                    v.add(rs.getString("emailid"));
                    v.add(rs.getString("userpassword"));
                    v.add(rs.getString("branchaddress"));
                }
                model.addRow(v);
            }
        } catch (SQLException e) {
         JOptionPane.showMessageDialog(null,"Error!"+e.getMessage()); 
    }
}
public void showTeacherData(){
    try {
        con2 = DriverManager.getConnection(url1, userid, userPass);
        pst2 = con2.prepareStatement("SELECT * FROM teachers");
        rs2 = pst2.executeQuery();
        ResultSetMetaData rst1 = rs2.getMetaData();
        cols2 = rst1.getColumnCount();
        DefaultTableModel model2 = (DefaultTableModel)Table3.getModel();
        
        while(rs2.next()){
            Vector v2 = new Vector();
            for (int i = 1;i<=cols2;i++){
                v2.add(rs2.getInt("id"));
                v2.add(rs2.getString("name"));
                v2.add(rs2.getString("email"));
                v2.add(rs2.getString("subject"));
                v2.add(rs2.getString("phone"));
            }
            model2.addRow(v2);
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,"Error! happen "+e.getMessage()); 
    }
}
public void showTableData(){
    try {
        con1 = DriverManager.getConnection(url1,userid,userPass);
        pst = con.prepareStatement("SELECT * FROM studentsoftware.stdinfo");
        rs1 = pst.executeQuery();
        ResultSetMetaData rst = rs1.getMetaData();
        cols1 = rst.getColumnCount();
        DefaultTableModel model1 = (DefaultTableModel)Table2.getModel();
        while (rs1.next()){
            Vector v1 = new Vector();
            for (int i = 1;i<=cols1;i++){
                v1.add(rs1.getInt("id"));
                v1.add(rs1.getString("StudentName"));
                v1.add(rs1.getString("Fathersname"));
                v1.add(rs1.getString("Mothersname"));
                v1.add(rs1.getString("Address"));
                v1.add(rs1.getString("class"));
                v1.add(rs1.getString("Batchname"));
                v1.add(rs1.getString("BranchAdd"));
                
            }
            model1.addRow(v1);
            
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null,"Error!"+e.getMessage()); 
    }
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JTextField BatchNameTxt;
    private javax.swing.JTextField BranchAddTxt;
    private javax.swing.JTextField BranchAddressTxt;
    private javax.swing.JLabel CloseTab;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField EmailIdTxt;
    private javax.swing.JTextField FatherTxt;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JLabel HeadingTab;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JLabel LogOutTab;
    private javax.swing.JTextField MotherTxt2;
    private javax.swing.JTextField NewClass;
    private javax.swing.JButton RefreshBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JTextField StudentNameTxt;
    private javax.swing.JButton StudentRefreshBtn;
    private javax.swing.JButton StudentRefreshBtn1;
    private javax.swing.JButton StudentSaveBtn;
    private javax.swing.JTextField StudentSearchTxt;
    private javax.swing.JLabel StudentTab;
    private javax.swing.JButton StudentUpdateBtn;
    private javax.swing.JPanel StudentsPanel;
    private javax.swing.JPanel TABSPANEL;
    private javax.swing.JTable Tab;
    private javax.swing.JTable Table2;
    private javax.swing.JTable Table3;
    private javax.swing.JButton TeacherDataDeleteBtn;
    private javax.swing.JButton TeacherDataRefreshBtn;
    private javax.swing.JTextField TeacherEmailTxt;
    private javax.swing.JTextField TeacherNameTxt;
    private javax.swing.JTextField TeacherNameTxt1;
    private javax.swing.JTextField TeacherNumberTxt;
    private javax.swing.JButton TeacherSavebtn;
    private javax.swing.JTextField TeacherSubjectTxt;
    private javax.swing.JButton TeacherUpdateBtn;
    private javax.swing.JPanel TeachersPanel;
    private javax.swing.JLabel TeachersTab;
    private javax.swing.JTextField UserNameTxt;
    private javax.swing.JTextField UserPassTxt;
    private javax.swing.JLabel UserTab;
    private javax.swing.JPanel UsersPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel sideBar;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
